[build]
  command = "npm run build"
  publish = "dist"
  environment = { SECRETS_SCAN_OMIT_KEYS = "VITE_AIRTABLE_TABLE_NAME,VITE_AIRTABLE_PAT,VITE_AIRTABLE_BASE_ID" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
